# The Python Programming Language: Functions

In [ ]:
x = 1
y = 2
x + y

In [ ]:
x

`add_numbers` es una funcion que toma dos numeros y los suma.


In [ ]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

`add_numbers` actualizada para tomar un tercer parametro opcional. Usar `print` permite imprimir multiples expresion dentro de una misma celda.

In [1]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


`add_numbers` actualizada para tomar un paramtero _flag_ opcional.

In [ ]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Asignar la funcion `add_numbers` a la variable `a`.

In [ ]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

# The Python Programming Language: Types and Sequences

Uso de `type` para retornar el tipo del objeto.

In [ ]:
type('This is a string')

In [ ]:
type(None)

In [ ]:
type(1)

In [ ]:
type(1.0)

In [ ]:
type(add_numbers)

Las tuplas son estructuras de datos inmutables (no se pueden alterar)

In [ ]:
x = (1, 'a', 2, 'b')
type(x)

Listas son estructuras de datos mutables.

In [ ]:
x = [1, 'a', 2, 'b']
type(x)

Usar `append` para adjuntar un objeto a una lista.

In [ ]:
x.append(3.3)
print(x)

Esto es un ejemplo de como hacer un loop a traves de cada elemento en la lista.

In [ ]:
for item in x:
    print(item)

o usando un operador para indexar

In [ ]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

Usar `+` para concatenar listas.

In [ ]:
[1,2] + [3,4]

Usar `*` para repetir listas.

In [ ]:
[1]*3

Usar el operador `in` para revisar si algo esta en la lista.

In [ ]:
1 in [1, 2, 3]

Ahora veamos strings. Usen notacion de brackets para partir un string.

In [ ]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters


Esto va a regresar el ultimo elemento del string.

In [ ]:
x[-1]

Esto va a retornar el pedazo empezando desde el 4to elemento desde el final y parando antes del segundo elemento desde el final.

In [ ]:
x[-4:-2]

Este es un slice desde el principio del string que para antes del tercer elemento.

In [ ]:
x[:3]

y este es un slice empezando desde el tercer elemento del string hasta el final.

In [ ]:
x[3:]

In [ ]:
firstname = 'Francisco'
lastname = 'Sosa'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Fran' in firstname)


`split` regresa una lista de todas las palabras en un string, o una lista partida en un caracter en especifico.

In [ ]:
firstname = 'Francisco Jose Sosa Hurtarte'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Francisco Jose Sosa Hurtarte'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Asegurense de convertir objetos a strings antes de concatenar.

In [ ]:
'Chris' + 2

In [ ]:
'Chris' + str(2)

Los diccionarios asociacn llaves con valores.

In [ ]:
x = {'Francisco Sosa': 'fjsosa@uvg.edu.gt', 'Bill Gates': 'billg@microsoft.com'}
x['Francisco Sosa'] # Retrieve a value by using the indexing operator


In [ ]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

Iterar sobre todas las llaves:

In [ ]:
for name in x:
    print(x[name])

Iterar sobre todos los valores.

In [ ]:
for email in x.values():
    print(email)

Iterar sobre todos los items en la lista.

In [ ]:
for name, email in x.items():
    print(name)
    print(email)

Se puede desempacar una secuencia a diferentes variables:

In [ ]:
x = ('Francisco', 'Sosa', 'fjsosa@uvg.edu.gt')
fname, lname, email = x

In [ ]:
fname

In [ ]:
lname

Asegurense que el numero de valores que estan desempacando sea igual al numero de variables que estan asignando.

In [ ]:
x = ('Francisco', 'Sosa', 'fjsosa@uvg.edu.gt', 'Guatemala')
fname, lname, email = x

# The Python Programming Language: More on Strings

In [ ]:
print('Francisco' + 2)

In [ ]:
print('Francisco' + str(2))

Python tiene metodos convenientes para formatear strings.

In [ ]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


# Leyendo y escribiendo archivos CSV

Vamos a importar el file de datos `mpg.csv` que contiene data para 234 carros.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [ ]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

`csv.Dictreader` ha leido cada fila de nuestro csv como un diccionario. `len` nos muestra que nuestra lista esta compuesta de 234 diccionarios.

In [ ]:
len(mpg)

`keys` nos da los nombres de las columnas de nuestro csv.

In [ ]:
mpg[0].keys()

Asi es como se calcula el promedio de cty fuel economy a traves de todos los carros. Todos los valores en el diccionario son strings, asi que tenemos que convertirlos a floats.

In [ ]:
sum(float(d['cty']) for d in mpg) / len(mpg)

De esta forma calculamos el hwy fuel economy de todos los carros.

In [ ]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

Usen `set` para regresar los valores unicos para el numero de cilindros que tienen los carros en nuestro dataset.

In [ ]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

Este es un ejemplo mas complejo donde estamos agrupando los carros por numero de cilindors y encontrando el cty mpg promedio para cada grupo.

In [ ]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

Usen `set` para retornar los valores unicos para los tipos de class en nuestro dataset.

In [ ]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

Este es un ejemplo de como encontrar el hwy promedio para cada clase de vehiculo en nuestro dataset.

In [ ]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

# The Python Programming Language: Dates and Times

In [ ]:
import datetime as dt
import time as tm

`time` regresa el tiempo actual en segundos desde Epoch. (Enero 1, 1970)

In [ ]:
tm.time()

Convertir el timestamp a un datetime.

In [ ]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

Atributos utiles de datetime:

In [ ]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

`timedelta` es una duracion expresando la diferencia entre dos fechas.

In [ ]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

`date.today` regresa la fecha local actual.

In [ ]:
today = dt.date.today()

In [ ]:
today - delta # the date 100 days ago

In [ ]:
today > today-delta # compare dates

# The Python Programming Language: Objects and map()

Un ejemplo de una clase en python:

In [ ]:
class Person:
    department = 'Department of Statistics' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [ ]:
person = Person()
person.set_name('Francisco Sosa')
person.set_location('Guatemala City, Guatemala')
print('{} lives in {} and works in the department {}'.format(person.name, person.location, person.department))

Este es un ejemplo de mapear la funcion `min` a entre dos listas.

In [2]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

Ahora iteremos a traves del objeto de map para ver los valores.

In [3]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


# The Python Programming Language: Lambda and List Comprehensions

Este es un ejemplo de una lambda que toma tres parametros y suma los primeros dos.

In [ ]:
my_function = lambda a, b, c : a + b

In [ ]:
my_function(1, 2, 3)

Iteremos desde 0 a 999 y regresemos los numeros pares.

In [ ]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

Ahora lo mismo pero con un list comprehension.

In [ ]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

# The Python Programming Language: Numerical Python (NumPy)

In [5]:
import numpy as np

## Creando arreglos

Crear una lista y convertirla a un NumPy array.

In [ ]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

O pasar la lista de forma directa

In [6]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Pasar una lista de listas para crear un arreglo multidimensional.

In [ ]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

Usen el metodo `shape` para encontrar las dimensiones del arreglo. (filas, columnas)

In [ ]:
m.shape

`arange` regresa valores espaciados uniformemente dentro de un intervalo.

In [ ]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

`reshape` regresa un arreglo con la misma data en una nueva forma (`shape`)

In [ ]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

`linspace` regresa numeros espeacidos uniformemente sobre un intervalo especificado.

In [ ]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

`resize` cambia la forma y tamanio del array in-place.

In [ ]:
o.resize(3, 3)
o

`ones` regresa un nuevo arreglo de un dado tamanio y tipo, lleno de unos.

In [ ]:
np.ones((3, 2))

`zeros` regresa un nuevo arreglo de un dado tamanio y tipo, lleno de ceros.

In [ ]:
np.zeros((2, 3))

`eye` regresa un arreglo 2-D con unos en la diagonal y ceros en los demas.

In [ ]:
np.eye(3)

`diag` extrae una diagonal o construye un arreglo diagonal

In [7]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Crear un arrelgo usando listas repetidas (o ver `np.tile`)

In [ ]:
np.array([1, 2, 3] * 3)

Repetir elementos de un arreglo usando `repeat`

In [ ]:
np.repeat([1, 2, 3], 3)

#### Combinar arreglos

In [ ]:
p = np.ones([2, 3], int)
p

Usen `vstack` para apilar arreglos en secuencia vertical (por filas)

In [ ]:
np.vstack([p, 2*p])

Usen `hstack` para apilar arreglos en secuencia horizontal (por columnas).

In [ ]:
np.hstack([p, 2*p])

## Operaciones


Usen `+`, `-`, `*`, `/` y `**` para realizar estas operaciones elemento por elemento (element wise)

In [ ]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

In [ ]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

In [ ]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [ ]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

In [ ]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

Veamos como transponer matrices. Transponer permuta las dimensiones de la matriz.

In [8]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

La forma del arreglo `z` es `(2,3)` antes de la traspuesta.

In [9]:
z.shape

(2, 3)

Usen `.T` para obtener la traspuesta.

In [10]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

El numero de filas fue cambiado por el numero de columnas.

In [ ]:
z.T.shape

Usen `.dtype` para ver el tipo de dato de los elementos en el arreglo.

In [ ]:
z.dtype

Usen `.astype` para castear a un tipo en especifico.

In [ ]:
z = z.astype('f')
z.dtype

## Funciones matematicas

NumPy tiene muchas funciones matematicas que pueden ser realizadas sobre arreglos.

In [ ]:
a = np.array([-4, -2, 1, 3, 5])

In [ ]:
a.sum()

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.mean()

In [ ]:
a.std()

`argmax` y `argmin` regresan el indice de los valores maximos y minimos en el arreglo.

In [ ]:
a.argmax()

In [ ]:
a.argmin()

## Indexing / Slicing

In [ ]:
s = np.arange(13)**2
s

Usar notacion de bracket para obtener el valor en un indice especifico. Recuerden que el indice empieza en cero.

In [ ]:
s[0], s[4], s[-1]

Usen `:` para indicar el rango. `array[start:stop]`

Dejar `start` o `stop` vacios va a usar el principio/fin del arreglo por default.

In [ ]:
s[1:5]

Usen negativos para contar hacia atras.

In [ ]:
s[-4:]

Un segundo `:` puede ser utilizado para indicar el tamanio del paso. `array[start:stop:stepsize]`

Aqui estamos empezando en el quinto elemento desde el final, contando hacia atras por 2 hasta llegar al principio del arreglo.

In [ ]:
s[-5::-2]

Veamos un arreglo multidimensional.

In [ ]:
r = np.arange(36)
r.resize((6, 6))
r

Usen notacion de bracket para partir: `array[row, column]`

In [ ]:
r[2, 2]

Y usen `:` para seleccionar un rango de filas o columnas

In [ ]:
r[3, 3:6]

Aqui estamos seleccionando todas las filas hasta (pero no incluyendo) la fila 2, y todas las columnas hasta (no incluyendo) la ultima.

In [ ]:
r[:2, :-1]

Este es un slice de la ultima fila, y solo cualquier otra semana.

In [ ]:
r[-1, ::2]

Tambien podemos realizar indices condicionales. Aqui estamos seleccionando valores del arreglo que son mayores a 30. (Tambien vean `np.where`)

In [ ]:
r[r > 30]

Aqui vamos a asignar todos los valores en el arreglo que son mayores a 30 al valor de 30.

In [ ]:
r[r > 30] = 30
r

## Copiando Data

Tengan cuidado con copiar y modificar arreglos en NumPy!

`r2` es un slice de `r`

In [ ]:
r2 = r[:3,:3]
r2

Asignen el valor de este slice a cero (`[:]` selecciona el arreglo entero)

In [ ]:
r2[:] = 0
r2

`r` tambien cambio!

In [11]:
r

NameError: name 'r' is not defined

Para evitar esto, usen `r.copy` para crear una copia que no va a afectar el arreglo original.

In [ ]:
r_copy = r.copy()
r_copy

Ahora cuando modifiquemos `r_copy`, `r` no va a cambiar.

In [ ]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)


### Iterando sobre arreglos

Creemos un nuevo arreglo 4x3 de numeros aleatorios entre 0-9

In [ ]:
test = np.random.randint(0, 10, (4,3))
test

Iterar por fila:

In [ ]:
for row in test:
    print(row)

Iterar por indice:

In [ ]:
for i in range(len(test)):
    print(test[i])

Iterar por fila e indice:

In [ ]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

Usen `zip` para iterar sobre multiples arreglos.

In [ ]:
test2 = test**2
test2

In [ ]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)